### ISSUE TITLE
"Schedule meeting" button goes nowhere

### ISSUE THREAD

**Issue by BraydenTW** [hashirshoaeb/portfolio#11]
Hey there! When I click the "Schedule meeting" button at the bottom of your site, it goes nowhere.

Just though I would let you know.

**Comment by hashirshoaeb** [comment]
Thank you for letting me know. I'm aware of it. I have planned to integrate Calendly link, but not getting enough time for it.

**Comment by hashirshoaeb** [comment]
Duplicate of #9 , so closing it.
