### ISSUE TITLE
Add calendly

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/portfolio#9]

**Comment by dinithminura** [comment]
Hi @hashirshoaeb,
First of all, I want to thank you for this nice template. I really appreciate it.
I noticed that the "Schedule Meeting" button currently redirects to topmate.io. For this issue, are you looking to integrate Calendly directly into the portfolio for booking time slots, or just to include a Calendly link within the Contact buttons?

Note: For users using Calendly, you can simply add a button or update the one in the `config.js` file with the link `https://calendly.com/your_user_name`

**Comment by hashirshoaeb** [comment]
No thanks. Adding Top mate is intentional.
